// Generated by https://pagedraw.io/pages/6103
import Folderlistelement from './folderlistelement';
import Createnote from './createnote';
import React from 'react';
import './app.css';

function render() {
    return <div className="app">
        <div className="app-0">
            <div className="app-app-1">
                <div className="app-0-0-0">
                    <div className="app-0-0-0-0">
                        <div className="app-0-0-0-0-0">
                            <div className="app-title-3">MeDB</div>
                        </div>
                        <div className="app-0-0-0-0-1">
                            <div className="app-0-0-0-0-1-0">
                                { this.props.rootFolderList.map((elem, i) => {
                                    return <div key={i} className="app-foldercontainer-0">
                                        <div className="app-0-0-0-0-1-0-0-0-0">
                                            <div className="app-folderelement-0">
                                                <Folderlistelement state={elem.state} name={elem.name} contents={elem.contents} /> 
                                            </div>
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                    </div>
                    <div className="app-createnote_instance-3">
                        <Createnote content={this.props.content} filename={this.props.filename} handleContentChange={this.props.handleContentChange} handleFilenameChange={this.props.handleFilenameChange} handleSaveNote={this.props.handleSaveNote} /> 
                    </div>
                </div>
                <div className="app-0-0-1">
                    <div className="app-syncbutton-4">Sync </div>
                </div>
                <div className="app-0-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}