// Generated by https://pagedraw.io/pages/6103
import Titlebar from './titlebar';
import Search from './search';
import Folderlistelement from './folderlistelement';
import Createnote from './createnote';
import React from 'react';
import './app.css';

function render() {
    return <div className="app">
        <div className="app-0">
            <div className="app-app-1">
                <div className="app-0-0-0">
                    <div className="app-titlebar_instance-5">
                        <Titlebar /> 
                    </div>
                </div>
                <div className="app-0-0-1">
                    <div className="app-page-6">
                        <div className="app-0-0-1-0-0">
                            <div className="app-leftcolumn-2">
                                <div className="app-0-0-1-0-0-0-0">
                                    <div className="app-yourfiles-2">Your Files</div>
                                </div>
                                <div className="app-0-0-1-0-0-0-1">
                                    <div className="app-search_instance-5">
                                        <Search handleSearchQueryChange={this.props.handleSearchQueryChange} handleExpand={this.props.handleExpand} searchResultList={this.props.searchResultList} /> 
                                    </div>
                                </div>
                                <div className="app-0-0-1-0-0-0-2">
                                    <div className="app-0-0-1-0-0-0-2-0">
                                        { this.props.rootFolderList.map((elem, i) => {
                                            return <div key={i} className="app-foldercontainer-0">
                                                <div className="app-0-0-1-0-0-0-2-0-0-0-0">
                                                    <div className="app-folderelement-0">
                                                        <Folderlistelement state={elem.state} name={elem.name} contents={elem.contents} handleExpand={this.props.handleExpand} /> 
                                                    </div>
                                                </div>
                                            </div>;
                                        }) }
                                    </div>
                                </div>
                            </div>
                            <div className="app-rightcolumn-2">
                                <div className="app-0-0-1-0-0-1-0">
                                    <div className="app-yourfiles-7">Add a file</div>
                                </div>
                                <div className="app-0-0-1-0-0-1-1">
                                    <div className="app-createnote_instance-3">
                                        <Createnote content={this.props.content} filename={this.props.filename} handleContentChange={this.props.handleContentChange} handleFilenameChange={this.props.handleFilenameChange} handleCommit={this.props.handleSaveNote} handlePull={this.props.handlePull} handlePush={this.props.handlePush} lastCommit={this.props.lastCommit} lastPull={this.props.lastPull} remoteAheadBy={this.props.remoteAheadBy} localAheadBy={this.props.localAheadBy} /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="app-0-0-1-0-1" /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}