// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './collapsed.css';

function render() {
    return <div className="collapsed">
        <div className="collapsed-0">
            <div className="collapsed-collapsed-3">
                <div className="collapsed-0-0-0">
                    <div className="collapsed-0-0-0-0">
                        <div className="collapsed-0-0-0-0-0">
                            <div className="collapsed-0-0-0-0-0-0">
                                <div className="collapsed-0-0-0-0-0-0-0">
                                    <div className="collapsed-0-0-0-0-0-0-0-0">
                                        <div className="collapsed-text_4">Folder Name</div>
                                    </div>
                                </div>
                                <div className="collapsed-0-0-0-0-0-0-1">
                                    <div className="collapsed-0-0-0-0-0-0-1-0">
                                        <div className="collapsed-text_4-1">Folder Name</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="collapsed-0-0-0-1">
                        <div className="collapsed-0-0-0-1-0">
                            <div className="collapsed-0-0-0-1-0-0">
                                <div className="collapsed-0-0-0-1-0-0-0">
                                    <div className="collapsed-0-0-0-1-0-0-0-0">
                                        <div className="collapsed-text_5">[+]</div>
                                    </div>
                                </div>
                                <div className="collapsed-0-0-0-1-0-0-1">
                                    <div className="collapsed-0-0-0-1-0-0-1-0">
                                        <div className="collapsed-text_5-4">[+]</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}