// Generated by https://pagedraw.io/pages/6103
import Gitoptions from './gitoptions';
import React from 'react';
import './createnote.css';

function render() {
    return <div className="createnote">
        <div className="createnote-0">
            <div className="createnote-createnote-3">
                <div className="createnote-0-0-0">
                    <input type="text" placeholder="Filepath" value={this.props.filename} onChange={this.props.handleFilenameChange} className="createnote-filenameinput-7" /> 
                </div>
                <div className="createnote-0-0-1">
                    <textarea placeholder="Enter text..." value={this.props.content} onChange={this.props.handleContentChange} className="createnote-contentinput-1" /> 
                </div>
                <div className="createnote-0-0-2">
                    <div className="createnote-gitoptions_instance-9">
                        <Gitoptions handleCommit={this.props.handleCommit} handlePull={this.props.handlePull} handlePush={this.props.handlePush} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}