// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './createnote.css';

function render() {
    return <div className="createnote">
        <div className="createnote-0">
            <div className="createnote-createnote-3">
                <div className="createnote-0-0-0">
                    <div className="createnote-notedescription-2">
                        Create a quick note
                    </div>
                </div>
                <div className="createnote-0-0-1">
                    <textarea placeholder="Enter text..." className="createnote-noteinput-1" /> 
                </div>
                <div className="createnote-0-0-2">
                    <div onClick={this.props.handleSaveNote} className="createnote-savebutton-2">
                        <div className="createnote-0-0-2-0-0">
                            <div className="createnote-text_3">Save</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}