// Generated by https://pagedraw.io/pages/6103
import ReactMarkdown from 'react-markdown'
import Titlebar from './titlebar';
import Viewstategroup from './viewstategroup';
import Filecontent from './filecontent';
import Gitoptions from './gitoptions';
import React from 'react';
import './editfile.css';

function render() {
    return <div className="editfile">
        <div className="editfile-0">
            <div className="editfile-editfile-4">
                <div className="editfile-0-0-0">
                    <div className="editfile-titlebar_instance-5">
                        <Titlebar /> 
                    </div>
                </div>
                <div className="editfile-0-0-1">
                    <div className="editfile-page-1">
                        <div className="editfile-0-0-1-0-0">
                            <div className="editfile-viewstategroup_instance-0">
                                <Viewstategroup handleClick={this.props.handleViewStateChange} state={this.props.viewState} /> 
                            </div>
                            <div className="editfile-0-0-1-0-0-1">
                                <div className="editfile-0-0-1-0-0-1-0">
                                    <div className="editfile-filename-8">
                                        { this.props.fileName }
                                    </div>
                                    <div className="editfile-0-0-1-0-0-1-0-1" /> 
                                </div>
                            </div>
                        </div>
                        <div className="editfile-0-0-1-0-1">
                            <div className="editfile-fileidentifier-8">
                                { this.props.fileID }
                            </div>
                            <div className="editfile-0-0-1-0-1-1" /> 
                        </div>
                        <div className="editfile-0-0-1-0-2">
                            <div className="editfile-rectangle_9">
                                <div className="editfile-0-0-1-0-2-0-0">
                                    <div className="editfile-0-0-1-0-2-0-0-0" /> 
                                    <div className="editfile-filecontent_instance-4">
                                        <Filecontent state={this.props.viewState} fileContent={this.props.fileContent} handleContentChange={this.props.handleContentChange} /> 
                                    </div>
                                    <div className="editfile-0-0-1-0-2-0-0-2" /> 
                                </div>
                            </div>
                        </div>
                        <div className="editfile-0-0-1-0-3">
                            <div className="editfile-gitoptions_instance-0">
                                <Gitoptions handleCommit={this.props.handleCommit} handlePull={this.props.handlePull} handlePush={this.props.handlePush} lastCommit={this.props.lastCommit} lastPull={this.props.lastPull} remoteAheadBy={this.props.remoteAheadBy} localAheadBy={this.props.localAheadBy} /> 
                            </div>
                            <div className="editfile-0-0-1-0-3-1" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}