// Generated by https://pagedraw.io/pages/6103
import ReactMarkdown from 'react-markdown'
import React from 'react';
import './filecontent.css';

function render() {
    return <div className="filecontent">
        { (this.props.state == "editing") ?
            <div className="filecontent-0-0">
                <div className="filecontent-0-0-0">
                    <div className="filecontent-editing-7">
                        <div className="filecontent-0-0-0-0-0">
                            <textarea value={this.props.fileContent} onChange={this.props.handleContentChange} className="filecontent-editcontent-5" /> 
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "viewing") ?
            <div className="filecontent-1-0">
                <div className="filecontent-1-0-0">
                    <div className="filecontent-viewing-2">
                        <div className="filecontent-1-0-0-0-0">
                            <div className="filecontent-text_2">
                                <ReactMarkdown source={this.props.fileContent} />
                            </div>
                        </div>
                        <div className="filecontent-1-0-0-0-1" /> 
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}