// Generated by https://pagedraw.io/pages/6103
import Folderlist from './folderlist';
import React from 'react';
import './folderlistelement.css';

function render() {
    return <div className="folderlistelement">
        { (this.props.state == "expanded") ?
            <div className="folderlistelement-0-0">
                <div className="folderlistelement-0-0-0">
                    <div className="folderlistelement-expanded-3">
                        <div className="folderlistelement-0-0-0-0-0">
                            <div className="folderlistelement-rectangle_7">
                                <div className="folderlistelement-0-0-0-0-0-0-0">
                                    <div className="folderlistelement-nestedlistelement-7">
                                        <Folderlist name={this.props.name} contents={this.props.contents} handleExpand={this.props.handleExpand} /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "collapsed") ?
            <div className="folderlistelement-1-0">
                <div className="folderlistelement-1-0-0">
                    <div className="folderlistelement-collapsed-4">
                        <div className="folderlistelement-1-0-0-0-0">
                            <div className="folderlistelement-rectangle_4">
                                <div className="folderlistelement-1-0-0-0-0-0-0">
                                    <div className="folderlistelement-rectangle_2">
                                        <div className="folderlistelement-1-0-0-0-0-0-0-0-0">
                                            <div className="folderlistelement-name-1">
                                                { this.props.name }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="folderlistelement-rectangle_3">
                                        <div className="folderlistelement-1-0-0-0-0-0-0-1-0">
                                            <div onClick={this.props.handleExpand} className="folderlistelement-plus-4">
                                                {"[+]"}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "file") ?
            <div className="folderlistelement-2-0">
                <div className="folderlistelement-2-0-0">
                    <div className="folderlistelement-file-3">
                        <div className="folderlistelement-2-0-0-0-0">
                            <div className="folderlistelement-rectangle_6">
                                <div className="folderlistelement-2-0-0-0-0-0-0">
                                    <div className="folderlistelement-rectangle_2-5">
                                        <div className="folderlistelement-2-0-0-0-0-0-0-0-0">
                                            <div className="folderlistelement-name-5">
                                                { this.props.name }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="folderlistelement-rectangle_3-2">
                                        <div className="folderlistelement-2-0-0-0-0-0-0-1-0">
                                            <div onClick={this.props.handleExpand} className="folderlistelement-minus-4">
                                                {"[open]"}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "expandedEmpty") ?
            <div className="folderlistelement-3-0">
                <div className="folderlistelement-3-0-0">
                    <div className="folderlistelement-expandedempty-0">
                        <div className="folderlistelement-3-0-0-0-0">
                            <div className="folderlistelement-rectangle_5">
                                <div className="folderlistelement-3-0-0-0-0-0-0">
                                    <div className="folderlistelement-rectangle_2-1">
                                        <div className="folderlistelement-3-0-0-0-0-0-0-0-0">
                                            <div className="folderlistelement-name-3">
                                                { this.props.name }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="folderlistelement-rectangle_3-6">
                                        <div className="folderlistelement-3-0-0-0-0-0-0-1-0">
                                            <div onClick={this.props.handleExpand} className="folderlistelement-minus-42">
                                                {"[-]"}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}