// Generated by https://pagedraw.io/pages/6103
import Folderlistelement from './folderlistelement';
import React from 'react';
import './folderlist.css';

function render() {
    return <div className="folderlist">
        <div className="folderlist-0">
            <div className="folderlist-folderlist-3">
                <div className="folderlist-0-0-0">
                    <div className="folderlist-containinginstance-8">
                        <Folderlistelement state={"expandedEmpty"} name={this.props.name} contents={[]} /> 
                    </div>
                </div>
                <div className="folderlist-0-0-1">
                    <div className="folderlist-0-0-1-0">
                        { this.props.contents.map((content, i) => {
                            return <div key={i} className="folderlist-nestedinstancecontainer-5">
                                <div className="folderlist-0-0-1-0-0-0-0">
                                    <div className="folderlist-nestedinstance-7">
                                        <Folderlistelement state={content.state} name={content.name} contents={content.contents} /> 
                                    </div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
                <div className="folderlist-0-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}