// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './gitoptions.css';

function render() {
    return <div className="gitoptions">
        <div className="gitoptions-0">
            <div className="gitoptions-gitoptions-0">
                <div className="gitoptions-0-0-0">
                    <div onClick={this.props.handleCommit} className="gitoptions-commitbutton-6">
                        <div className="gitoptions-0-0-0-0-0">
                            <div className="gitoptions-text_3">Commit</div>
                        </div>
                    </div>
                </div>
                <div className="gitoptions-0-0-1">
                    <div onClick={this.props.handlePull} className="gitoptions-commitbutton-5">
                        <div className="gitoptions-0-0-1-0-0">
                            <div className="gitoptions-text_3-5">Pull</div>
                        </div>
                    </div>
                </div>
                <div className="gitoptions-0-0-2">
                    <div onClick={this.props.handlePush} className="gitoptions-commitbutton-0">
                        <div className="gitoptions-0-0-2-0-0">
                            <div className="gitoptions-text_3-7">Push</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}