// Generated by https://pagedraw.io/pages/6103
import Folderlistelement from './folderlistelement';
import React from 'react';
import './search.css';

function render() {
    return <div className="search">
        <div className="search-0">
            <div className="search-search-8">
                <div className="search-0-0-0">
                    <input type="text" placeholder="Search..." onChange={this.props.handleSearchQueryChange} className="search-filenameinput-8" /> 
                </div>
                <div className="search-0-0-1">
                    <div className="search-0-0-1-0">
                        { this.props.searchResultList.map((elem, i) => {
                            return <div key={i} className="search-foldercontainer-3">
                                <div className="search-0-0-1-0-0-0-0">
                                    <div className="search-folderelement-8">
                                        <Folderlistelement state={elem.state} name={elem.name} contents={elem.contents} handleExpand={this.props.handleExpand} /> 
                                    </div>
                                </div>
                                <div className="search-0-0-1-0-0-0-1" /> 
                            </div>;
                        }) }
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}