// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './titlebar.css';

function render() {
    return <div className="titlebar">
        <div className="titlebar-0">
            <div className="titlebar-titlebar-8">
                <div className="titlebar-0-0-0">
                    <div className="titlebar-rectangle-8">
                        <div className="titlebar-0-0-0-0-0">
                            <a href="/" className="titlebar-0-0-0-0-0-0">
                                <div className="titlebar-text-7">MeDB</div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}