// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './viewing.css';

function render() {
    return <div className="viewing">
        <div className="viewing-0">
            <div className="viewing-viewing-2">
                <div className="viewing-0-0-0">
                    <div className="viewing-text_2">
                        <ReactMarkdown source={this.props.fileContent} />
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}