// Generated by https://pagedraw.io/pages/6103
import React from 'react';
import './viewstategroup.css';

function render() {
    return <div className="viewstategroup">
        { (this.props.state == "viewing") ?
            <div className="viewstategroup-0-0">
                <div className="viewstategroup-0-0-0">
                    <div onClick={this.props.handleClick} className="viewstategroup-viewing-6">
                        <div className="viewstategroup-0-0-0-0-0">
                            <div className="viewstategroup-edittitle-9">Viewing</div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "editing") ?
            <div className="viewstategroup-1-0">
                <div className="viewstategroup-1-0-0">
                    <div className="viewstategroup-editing-2">
                        <div className="viewstategroup-1-0-0-0-0">
                            <div onClick={this.props.handleClick} className="viewstategroup-edittitle-0">
                                <div>Editing</div>
                                <br/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}